apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /database/data
