apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-identity-db-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteMany