apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  containers:
  - name: grafana
    image: grafana/grafana-enterprise
    ports:
    - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-node-port
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      nodePort: 30002


