apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-identity-db-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  storageClassName: prometheus
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
