apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 5s
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: "identity_api"
        scrape_interval: 3s
        static_configs:
          - targets: ["10.102.206.182:8080"]
      - job_name: "database"
        static_configs:
          - targets: ["10.96.34.26:9187"]

      
---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    database: prometheus
spec:
  volumes:
  - name: prometheus-volume
    persistentVolumeClaim:
      claimName: prometheus-pvc
  - name: config-volume
    configMap:
      name: prometheus-config
  containers:
  - name: prometheus
    image: prom/prometheus:latest
    ports:
    - containerPort: 9090
    volumeMounts:
    - name: prometheus-volume
      mountPath: "/prometheus"
    volumeMounts:
    - name: config-volume
      mountPath: "/etc/prometheus"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-cluster-ip
spec:
  type: ClusterIP
  selector:
    database: prometheus
  ports: 
  - protocol: TCP
    port: 9090
    targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-port
spec:
  type: NodePort
  selector:
    database: prometheus
  ports:
    - port: 9090
      nodePort: 30050

  
